{% set name = "ufolib2" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 891524052b3636a25b9a92f13f7fd8c24e15483bac96ccd0245ae947d127248b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - attrs >=20.1.0
    - fonttools >=4.0.0
    - fs
    - python >={{ python_min }}

test:
  imports:
    - ufoLib2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fonttools/ufoLib2
  summary: ufoLib2 is a UFO font processing library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
