{% set name = "ufolib2" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ufoLib2-{{ version }}.tar.gz
  sha256: 49f0dc7f72ccacfe7faefe0d53d37971d45664d8b0563ef36956fa7bfa55a2bd

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - attrs >=20.1.0
    - fonttools >=4.0.0
    - fs
    - python >=3.8

test:
  imports:
    - ufoLib2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/ufoLib2
  summary: ufoLib2 is a UFO font processing library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
