{% set name = "ufolib2" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad53201d11e12f61b5fc5c2a81cb14cdbe68647cca6c00150ea1c0a1a9c7a32b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - attrs >=20.1.0
    - fonttools >=4.0.0
    - fs
    - python >=3.8

test:
  imports:
    - ufoLib2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/ufoLib2
  summary: ufoLib2 is a UFO font processing library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
